---

- name: Create Redis Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: "{{ namespace_name }}"
        name: "{{ database_name }}-secret"
      data:
        redis-password: cmVkaXMtcGFzc3dvcmQ=